alias     pip='pip3'
alias ipython='ipython3'

alias      ll='ls -lFh'
alias      la='ls -a1'
alias       l='ls -1'
alias    grep='grep  --color=auto'
alias   fgrep='fgrep --color=auto'
alias   egrep='egrep --color=auto'
alias     dir='ls'
alias      ip='ip -color'
alias    dirs='dirs -lpv'
